### ISSUE TITLE
Not all windows affected by decorations

### ISSUE THREAD

**Issue by bunself** [AhoyISki/Firedecor#11]
With the default config from the readme I'll get most windows to show up with the expected decorations (ppsspp pictured) but neither of the terminal emulators I have installed (alacritty and kitty) do.
![20220618_05h36m12s_grim](https://user-images.githubusercontent.com/76822792/174424484-07bb906f-d118-4e83-9539-2f66e280f982.png)

![20220618_05h35m43s_grim](https://user-images.githubusercontent.com/76822792/174424481-d5a424c9-c624-42f9-b8e7-339cc6184ced.png)

**Comment by bunself** [comment]
windows also "hang over" the rounded border's corners with their square corners
![20220618_01h39m22s_grim](https://user-images.githubusercontent.com/76822792/174426175-e84bba53-074c-4103-aee5-a22e1f13ce67.png)

**Comment by AhoyISki** [comment]
Kitty has an option to disable its own window decorations, you can find it in the kitty website. I think allacritty probably has it too

**Comment by AhoyISki** [comment]
> windows also "hang over" the rounded border's corners with their square corners
> ![20220618_01h39m22s_grim](https://user-images.githubusercontent.com/76822792/174426175-e84bba53-074c-4103-aee5-a22e1f13ce67.png)
> 
> 

For this one, firedecor doesn't actually round corners, it just rounds its own window decorations, so you would be better off with either 0 width borders or no rounding on the bottom, which are both options in the configuration.

**Comment by bunself** [comment]
Do you know of any plugin/feature for wayfire that will round the corners?

**Comment by AhoyISki** [comment]
I think ammen99 might have created one
