### ISSUE TITLE
custom button not displayed

### ISSUE THREAD

**Issue by clemencyworld1** [AhoyISki/Firedecor#14]
Thanks for this great plugin.

So, following the instruction on github page; i created a folder ~/.config/firedecor/button-styles/guy. In it I placed 9 png files named:
close-hover.png    
minimize-hover.png    
toggle-maximize-hover.png
close.png         
 minimize.png          
toggle-maximize.png
close-pressed.png  
minimize-pressed.png  
toggle-maximize-pressed.png

I replaced "simple" with "guy" in button-style within wayfire,ini. Then restarted wayfire but the windows still use the default style.

Please, is there anything am doing wrong. I installed the package from AUR using yay as helper.

Thanks

**Comment by clemencyworld1** [comment]
![20220724_03h36m26s_grim](https://user-images.githubusercontent.com/42145055/180629824-3c294bb6-60aa-426c-bda7-ebf1a3ce2bc5.png)

**Comment by AhoyISki** [comment]
For hovered buttons, the ending word is `hovered`, not `hover` so they wouldn't work. But there was indeed a problem, that I have hopefully addressed in the latest commit. Please install and see if it works for you, It is working on my machine :).

![image](https://user-images.githubusercontent.com/91404038/180632857-c05b1c41-9fc7-4192-bd59-c3f558ee7ce6.png)

**Comment by clemencyworld1** [comment]
Thanks. Made the correction, rebuild and its showing now
