### ISSUE TITLE
Gradient Support? [Enhancement}

### ISSUE THREAD

**Issue by clemencyworld1** [AhoyISki/Firedecor#16]
Thanks for this wonderful software. I was an ardent user of sawfish window manager but switched over to wayfire since it became so buggy and troublesome. So far, everything is working fine save for some window eye candy which your plugin has addressed.

I am wondering if you have plans of adding gradient support. That would be a very nice addition in improving the appearance of wayfire windows.

#Am yet to wrap my head around the accent portion of firedecor.

**Comment by AhoyISki** [comment]
Sorry, I have since migrated to Hyprland, as such, I can't really promise any new developments on the plugin.

**Comment by clemencyworld1** [comment]
Sad
