### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by siduck** [AhoyISki/Firedecor#7]
Hi @AhoyISki great plugin, I have installed it but i dont see any change in the decorations 

![d](https://user-images.githubusercontent.com/59060246/168488131-fbdc8e47-69a3-4f5f-821f-e4a284b83196.png)

it just looks like the default window decor in wayfire ;(

**Comment by AhoyISki** [comment]
Have you updated your config?

**Comment by siduck** [comment]
> Have you updated your config?

yep

**Comment by siduck** [comment]
How do i get the decorations to  look like this

![image](https://user-images.githubusercontent.com/59060246/168488274-769a46fe-b5c8-4842-b5ac-c583af7848fb.png)

**Comment by AhoyISki** [comment]
Have you installed wayfire by `git clone`ing?

**Comment by siduck** [comment]
> Have you installed wayfire by `git clone`ing?

yep

**Comment by siduck** [comment]
```
[sid@sid ~]$ ls /usr/local/lib/wayfire/

lib              libcommand.so                 libextra-gestures.so  libidle.so     libplace.so               libsimple-tile.so   libwinshadows.so
libalpha.so      libcube.so                    libfast-switcher.so   libinvert.so   libpreserve-output.so     libswitcher.so      libwm-actions.so
libanimate.so    libdecoration.so              libfiredecor.so       libipc.so      libresize.so              libvswipe.so        libwobbly.so
libautostart.so  libdefault-config-backend.so  libfisheye.so         libmove.so     libscale-title-filter.so  libvswitch.so       libwrot.so
libblur.so       libexpo.so                    libgrid.so            liboswitch.so  libscale.so               libwindow-rules.so  libzoom.so
[sid@sid ~]$ 
```

**Comment by AhoyISki** [comment]
Check for a `/usr/bin/wayfire/libfiredecor.so`, if you find it, move it to to `/usr/local/bin/wayfire/`

**Comment by siduck** [comment]
> Check for a `/usr/lib/wayfire/libfiredecor.so`, if you find it, move it to to `/usr/local/lib/wayfire/`

i dont find it

**Comment by AhoyISki** [comment]
I have changed the directory in my comment

**Comment by siduck** [comment]
> I have changed the directory in my comment

i dont find it there

**Comment by siduck** [comment]
> ```
> [sid@sid ~]$ ls /usr/local/lib/wayfire/
> 
> lib              libcommand.so                 libextra-gestures.so  libidle.so     libplace.so               libsimple-tile.so   libwinshadows.so
> libalpha.so      libcube.so                    libfast-switcher.so   libinvert.so   libpreserve-output.so     libswitcher.so      libwm-actions.so
> libanimate.so    libdecoration.so              libfiredecor.so       libipc.so      libresize.so              libvswipe.so        libwobbly.so
> libautostart.so  libdefault-config-backend.so  libfisheye.so         libmove.so     libscale-title-filter.so  libvswitch.so       libwrot.so
> libblur.so       libexpo.so                    libgrid.so            liboswitch.so  libscale.so               libwindow-rules.so  libzoom.so
> [sid@sid ~]$ 
> ```

its already there

**Comment by AhoyISki** [comment]
Can you restart wayfire then

**Comment by siduck** [comment]
> Can you restart wayfire then

tried, no change :(

**Comment by AhoyISki** [comment]
The default firedecor configuration is supposed to look like regular wayfire

**Comment by AhoyISki** [comment]
To get it to look like the posted picture, you should look at the configs in the REAME.md

**Comment by siduck** [comment]
> Can you restart wayfire then
 
 oh so its supposed to look like default wayfire window decor by default?

**Comment by AhoyISki** [comment]
Yes, to get the white top, have a look at the accents feature

**Comment by siduck** [comment]
how do i change the button colors? i see them colored only when i hover on them, how can i keep the color permanent?

**Comment by AhoyISki** [comment]
That information is in the buttons section of the README

**Comment by siduck** [comment]
i have tried changing the options in default firedecor config in wayfire.ini but doesnt work

**Comment by AhoyISki** [comment]
The changes should apply on newly opened windows

**Comment by siduck** [comment]
ive tried it, no change at all. 

```

[firedecor]
active_accent = \#FFFFFFFF
active_border = \#222222AA
active_outline = \#000000FF
active_title = \#FFFFFFFF
border_size = 10 30 10 10
button_size = 20
button_style = firedecor
corner_radius = 20
debug_mode = false
extra_themes = 
font = sans-serif
font_size = 21
icon_size = 20
icon_theme = Papirus
ignore_views = none
inactive_accent = \#FFFFFFFF
inactive_border = \#333333DD
inactive_buttons = false
inactive_outline = \#000000FF
inactive_title = \#FFFFFFFF
layout = - P5 title | | minimize p maximize p close P5 -
max_title_size = 750
outline_size = 0
padding_size = 2
round_on = all
```

**Comment by AhoyISki** [comment]
Have you remembered to place `firedecor` in the `[plugins]` section

**Comment by AhoyISki** [comment]
?

**Comment by siduck** [comment]
> Have you remembered to place `firedecor` in the `[plugins]` section?

yes ofc lol, its the last plugin there

**Comment by AhoyISki** [comment]
Did you remove the `decoration` plugin?

**Comment by siduck** [comment]
no

**Comment by siduck** [comment]
lemme try and see

**Comment by AhoyISki** [comment]
Remove it then, you can only have one active decoration plugin at a time

**Comment by siduck** [comment]
oooo works :0

**Comment by AhoyISki** [comment]
For obvious reasons

**Comment by siduck** [comment]
@AhoyISki how do i change button colors?

**Comment by AhoyISki** [comment]
There is currently no way to do that

**Comment by siduck** [comment]
![d](https://user-images.githubusercontent.com/59060246/168489719-aff625a3-a226-453e-acad-bcc8cd69240a.png)

also is there a way to add bottom padding under the buttons?

**Comment by siduck** [comment]
> There is currently no way to do that

hmm so how does it takes those macos button colors? :thinking:

**Comment by AhoyISki** [comment]
> ![d](https://user-images.githubusercontent.com/59060246/168489719-aff625a3-a226-453e-acad-bcc8cd69240a.png)
> 
> also is there a way to add bottom padding under the title?

Not at the moment

**Comment by AhoyISki** [comment]
> > There is currently no way to do that
> 
> hmm so how does it takes those macos button colors? thinking

? The colors are already set to a reasonable standard, and none of the pictures hvae different colors on the buttons

**Comment by AhoyISki** [comment]
Don't know why I didn't do it like that the first time around

**Comment by siduck** [comment]
> I have changed things so that the titles, icons and buttons should now be vertically centered on the edges.

cool! it'd be nice to be able to change the colors of buttons tho. Currently they look dull with my colorscheme ;(

**Comment by AhoyISki** [comment]
Now the buttons will interpolate between 2 colors of your choosing!

**Comment by siduck** [comment]
@AhoyISki  thanks a lot!

![image](https://user-images.githubusercontent.com/59060246/168712881-1c7796ac-e3a9-4f06-b7dc-e70dad798c42.png)

Also I use wayfire-shadows, so i dont think you need to implement it :p
